http:
  middlewares:
    middlewares-compress:
      compress:
        minResponseBodyBytes: 1024
        encodings:
          - gzip
          - br
          - zstd
        excludedContentTypes:
          - text/event-stream
