# https://github.com/clockworksoul/docker-gc-cron
services:
  docker-gc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - socket_proxy
    volumes:
      - ${CONFIG_DIR:-./config}/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      CRON: "0 0 0 * * ?"
      FORCE_IMAGE_REMOVAL: "1"
      FORCE_CONTAINER_REMOVAL: "0"
      GRACE_PERIOD_SECONDS: "604800"
      DRY_RUN: "0"
      CLEAN_UP_VOLUMES: "1"
      TZ: ${TZ:-Asia/Shanghai}
      DOCKER_HOST: tcp://socket-proxy:2375
