networks:
  default:
    driver: bridge
  t3_proxy:
    name: t3_proxy
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
  ipv6_proxy:
    name: ipv6_proxy
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:dead:beef:ff00::/64

include:
  - ../../services/socket-proxy/compose.yml
  - ../../services/traefik/compose.yml
  - ../../services/docker-gc/compose.yml
  - ../../services/postgresql/compose.yml
  - ../../services/cli-proxy-api/compose.yml
  - ../../services/new-api/compose.yml
  - ../../services/vaultwarden/compose.yml
  - ../../services/wud/compose.yml
